import Head from 'next/head';
import Container from '@/layout/Container';

export default function About(): JSX.Element {
	return (
		<div>
			<Head>
				<title>About | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<div className='text-center pt-4 mt-5'>
					<h1 className='text-3xl md:text-5xl font-semibold'>Who am I?</h1>
					<p className='text-lg md:text-2xl font-extralight my-4 text-[#CCCCCC]'>
						If you and I are to become friends, <br /> I guess it’s about time I introduce myself.
					</p>
				</div>
			</Container>
		</div>
	);
}
