import Head from 'next/head';
import Container from '@/layout/Container';
import PageHeader from '@/components/shared/PageHeader';

export default function Articles(): JSX.Element {
	return (
		<div>
			<Head>
				<title>Articles | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<PageHeader title='Articles' intro='Sharing ideas and discoveries in a few words' />
			</Container>
		</div>
	);
}
