import Head from 'next/head';
import Container from '@/layout/Container';
import Layout from 'src/layout/Layout';

export default function Library(): JSX.Element {
	return (
		<Layout>
			<Head>
				<title>Articles | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<Container>
					<h1>Articles</h1>
				</Container>
			</Head>
		</Layout>
	);
}
