import Head from 'next/head';
import Link from 'next/link';
import Container from '@/layout/Container';
import BookCard from '@/components/library/BookCard';

const BOOK = {
	title: 'The 7 Habits of Highly Effective People ',
	author: 'Stephen R. Covey',
};

export default function Home(): JSX.Element {
	return (
		<div>
			<Head>
				<title>Home | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<div
					className='text-center pt-4 mt-16'
					style={{ backgroundImage: 'url(/lines.png)', backgroundRepeat: 'no-repeat', backgroundPosition: 'center' }}
				>
					<h1 className='text-[28px] md:text-5xl font-semibold'>
						Hello, I’m Mathieu Céraline{' '}
						<span role='img' aria-label='waving hand'>
							👋🏾
						</span>
					</h1>
					<p className='text-lg md:text-2xl font-extralight mb-6 lg:my-6 text-[#9197A4] dark:text-[#CCCCCF]'>
						I’m a Frontend Web Developer and Designer.
					</p>
					<button
						type='button'
						className='bg-primary-light dark:bg-primary-dark px-6 py-2 rounded-lg text-md'
						style={{
							background: ' linear-gradient(90deg, #FFA109 0%, #FFCA74 100%)',
							boxShadow: '0px 20px 20px -13px rgba(255, 185, 69, 0.4)',
						}}
					>
						Get to know me
					</button>
				</div>

				<main className='mt-40'>
					<div className='grid lg:grid-cols-[1fr,2fr] gap-10 '>
						<section>
							<h2 className='text-2xl font-bold'>Latest posts</h2>
							<p className='mt-2 mb-4 font-thin'>On design, code and creativity.</p>
							<Link href='/playground' passHref>
								<a>
									<div>
										<div
											className='h-64   bg-primary-light rounded-lg shadow-lg'
											style={{
												backgroundImage: 'url(https://source.unsplash.com/450x222/?write)',
												backgroundSize: 'cover',
											}}
										/>
									</div>
									<h3 className='mt-5 font-bold text-md'>Jerry, Personal Portfolio</h3>
								</a>
							</Link>
						</section>
						<section className=''>
							<h2 className='text-2xl font-bold'>What I've been working on</h2>
							<p className='mt-2 mb-4 font-thin'>Here is the last project I had fun with.</p>
							<Link href='/playground' passHref>
								<a>
									<div>
										<div
											className='h-64  bg-primary-light rounded-lg shadow-lg'
											style={{
												backgroundImage: 'url(https://source.unsplash.com/450x222/?computer)',
												backgroundSize: 'cover',
											}}
										/>
									</div>
									<h3 className='mt-5 font-bold text-md'>Jerry, Personal Portfolio</h3>
								</a>
							</Link>
						</section>
					</div>
					<div className='my-32 md:w-2/6 mx-auto'>
						<p className='text-2xl font-bold italic mb-2 text-center'>
							Here, a quote that particularly inspires me and that is very very long.
						</p>
						<p className='text-right'>- The author</p>
					</div>
					<div className='grid lg:grid-cols-[1fr,4fr] md:grid-cols-[1fr,2fr] sm:grid-cols-[1fr,1fr] gap-10 '>
						<section>
							<h2 className='text-2xl font-bold'>
								Library{' '}
								<span role='img' aria-label='book'>
									📘
								</span>
							</h2>
							<p className='mt-2 mb-4 font-thin'>On design, code and creativity.</p>
							<Link href='/playground' passHref>
								<a>
									<BookCard book={BOOK} />
									{/* <div
										style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										className='rounded-lg shadow-lg'
									>
										<Image src='/book-sample.jpg' alt='' height={454} width={301} className='rounded-lg ' />
										{/* <img src='/book-sample.jpg' alt='' className='rounded-lg shadow-lg' /> */}
									{/* <div
											className='h-96  bg-primary-light rounded-lg shadow-lg'
											style={{
												backgroundImage: 'url(https://source.unsplash.com/450x222/?book)',
												backgroundSize: 'cover',
											}}
										/> */}
									{/* </div>
									<h3 className='mt-5 font-bold text-md'>The 7 Habits of Highly Effective People</h3>
									<p>Stephen R. Covey</p> */}
								</a>
							</Link>
						</section>
						<section className=''>
							<h2 className='text-2xl font-bold'>
								Seeding ideas
								<span role='img' className='ml-1' aria-label='plant'>
									🌱
								</span>
							</h2>
							<p className='mt-2 mb-4 font-thin'>
								My recent explorations and uncomplete ideas on design, web development and creativty.
							</p>
							<div className='grid lg:grid-cols-[1fr,1fr,1fr] md:grid-cols-[1fr,1fr] gap-10 '>
								<Link href='/playground' passHref>
									<a>
										<div
											className='dark:bg-darkGrey  rounded-lg p-4 flex flex-col justify-center'
											style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										>
											<h3 className='text-md mb-2'>Best Accessibility Pratices for Web Developers</h3>
											<div>
												<span className='text-[#69AE22]'>
													<span role='img' className='mr-1' aria-label='plant'>
														🌱
													</span>
													{'  '}
													Seeding
												</span>
												<span className='text-[#C4C4C4]'>
													<span className='mx-3'>•</span>May 24th, 2021
												</span>
											</div>
										</div>
									</a>
								</Link>
								<Link href='/playground' passHref>
									<a>
										<div
											className='dark:bg-darkGrey rounded-lg p-4 h-full flex flex-col justify-center'
											style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										>
											<h3 className='text-md mb-2'>Mona Lisa isn’t who you think she is</h3>
											<div>
												<span className='text-[#69AE22]'>
													<span role='img' className='mr-1' aria-label='plant'>
														🌱
													</span>
													{'  '}
													Seeding
												</span>
												<span className='text-[#C4C4C4]'>
													<span className='mx-3'>•</span>May 24th, 2021
												</span>
											</div>
										</div>
									</a>
								</Link>
								<Link href='/playground' passHref>
									<a>
										<div
											className='dark:bg-darkGrey  rounded-lg p-4 flex flex-col justify-center'
											style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										>
											<h3 className='text-md mb-2'>Best Accessibility Pratices for Web Developers</h3>
											<div>
												<span className='text-[#69AE22]'>
													<span role='img' className='mr-1' aria-label='plant'>
														🌱
													</span>
													{'  '}
													Seeding
												</span>
												<span className='text-[#C4C4C4]'>
													<span className='mx-3'>•</span>May 24th, 2021
												</span>
											</div>
										</div>
									</a>
								</Link>
								<Link href='/playground' passHref>
									<a>
										<div
											className='dark:bg-darkGrey  rounded-lg p-4 flex flex-col justify-center'
											style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										>
											<h3 className='text-md mb-2'>Best Accessibility Pratices for Web Developers</h3>
											<div>
												<span className='text-[#69AE22]'>
													<span role='img' className='mr-1' aria-label='plant'>
														🌱
													</span>
													{'  '}
													Seeding
												</span>
												<span className='text-[#C4C4C4]'>
													<span className='mx-3'>•</span>May 24th, 2021
												</span>
											</div>
										</div>
									</a>
								</Link>
								<Link href='/playground' passHref>
									<a>
										<div
											className='dark:bg-darkGrey  rounded-lg p-4 h-full flex flex-col justify-center'
											style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										>
											<h3 className='text-md mb-2'>Mona Lisa isn’t who you think she is</h3>
											<div>
												<span className='text-[#69AE22]'>
													<span role='img' className='mr-1' aria-label='plant'>
														🌱
													</span>
													{'  '}
													Seeding
												</span>
												<span className='text-[#C4C4C4]'>
													<span className='mx-3'>•</span>May 24th, 2021
												</span>
											</div>
										</div>
									</a>
								</Link>
								<Link href='/playground' passHref>
									<a>
										<div
											className='dark:bg-darkGrey  rounded-lg p-4 h-full flex flex-col justify-center'
											style={{ boxShadow: '0px 4px 6px rgba(0, 0, 0, 0.68)' }}
										>
											<h3 className='text-md mb-2'>Mona Lisa isn’t who you think she is</h3>
											<div>
												<span className='text-[#69AE22]'>
													<span role='img' className='mr-1' aria-label='plant'>
														🌱
													</span>
													{'  '}
													Seeding
												</span>
												<span className='text-[#C4C4C4]'>
													<span className='mx-3'>•</span>May 24th, 2021
												</span>
											</div>
										</div>
									</a>
								</Link>
							</div>
						</section>
					</div>
				</main>
			</Container>
		</div>
	);
}
