import Head from 'next/head';

import Container from '@/layout/Container';

export default function Home(): JSX.Element {
	return (
		<div>
			<Head>
				<title>Home | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<p>Hello World</p>
			</Container>
		</div>
	);
}
