import Head from 'next/head';
import Container from '@/layout/Container';
import Layout from '@/layout/Layout';

export default function Library({ theme, toggleTheme }: { theme: any; toggleTheme: any }): JSX.Element {
	return (
		<Layout theme={theme} toggleTheme={toggleTheme}>
			<Head>
				<title>Library | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<div className='text-center pt-4 mt-5'>
					<h1 className='text-3xl md:text-5xl font-semibold'>Library</h1>
					<p className='text-lg md:text-xl font-extralight my-4 text-[#CCCCCC]'>
						Here are some of the books I have enjoyed and learned from lately.
					</p>
				</div>
			</Container>
		</Layout>
	);
}
