import Head from 'next/head';
import Container from '@/layout/Container';

export default function Playground(): JSX.Element {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<div className='text-center pt-4 mt-5'>
					<h1 className='text-3xl md:text-5xl font-semibold'>Playground</h1>
					<p className='text-lg md:text-xl font-extralight my-4 text-[#CCCCCC]'>
						I like to play, to experiment and discover new things and technologies. <br />
						If you’re curious, here are a few project I worked on recently.
					</p>
				</div>
			</Container>
		</div>
	);
}
