import Head from 'next/head';
import Container from '@/layout/Container';
import Layout from '@/layout/Layout';

export default function Playground({ theme, toggleTheme }: { theme: any; toggleTheme: any }): JSX.Element {
	return (
		<Layout theme={theme} toggleTheme={toggleTheme}>
			<Head>
				<title>Playground | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container>
				<div className='text-center pt-4 mt-5'>
					<h1 className='text-3xl md:text-5xl font-semibold'>Playground</h1>
					<p className='text-lg md:text-xl font-extralight my-4 text-[#CCCCCC]'>
						I like to play, to experiment and discover new things and technologies. <br />
						If you’re curious, here are a few project I worked on recently.
					</p>
				</div>
			</Container>
		</Layout>
	);
}
