import Container from '@/layout/Container';
import { gql } from '@apollo/client';
import client from '@/graphql/apollo-client';
import Image from 'next/dist/client/image';
import ImageCard from '@/components/shared/ImageCard';
import Head from 'next/dist/next-server/lib/head';

const PROJECT = {
	title: 'Audiophile',
	description:
		"Forecast is a project I put together after learning the basics of GraphQL. This application was the perfect way to improve my understanding of making queries and managing larger sets of data. In this project, I utilized OpenWeatherMap API to gather the weather data and injected this data based on the user's zip code input.",
};

export default function Project({ project }: { project: any }): JSX.Element {
	return (
		<>
			<Head>
				<title>{project.name} | Mathieu Céraline</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<Container className='my-14 relative'>
					<div className='grid md:grid-cols-[3fr,2fr] gap-10 mb-24'>
						<ImageCard cover={project.cover} className='h-80' />

						<div>
							<div className='mb-10 flex items-center justify-between'>
								<h1 className='text-3xl md:text-6xl font-extrabold'>{project.name}</h1>
								<div className=''>
									<a className='font-thin bg-primary-dark rounded py-2 px-4'>Live Demo</a>
								</div>
							</div>

							<p className='md:max-w-[750px]  md:text-left mb-4'>{PROJECT.description}</p>

							<div className='flex flex-wrap flex-1'>
								{project.skills && <span className='font-bold mr-2 '>Built with</span>}
								{project.skills && (
									<div className='flex  space-x-reverse flex-wrap items-center flex-1'>
										{project?.skills?.map((skill: any) => (
											<span className='mr-2' key={skill?.name}>
												<span className='flex items-center space-x-1'>
													<Image
														src={skill.icon.url}
														height={18}
														width={18}
														layout='fixed'
														alt={skill.name}
													/>
													<span>{skill?.name}</span>
												</span>
											</span>
										))}
									</div>
								)}
							</div>
						</div>
					</div>
					<div className='my-24'>
						{/* <h2 className='text-5xl font-thin mx-auto my-10'>Case Study</h2> */}
						<div className='grid gap-10 | md:grid-cols-[1fr,4fr] | xl:grid-cols-[1fr,2fr,1fr]'>
							<div className='space-y-2  | self-start md:border-r md:w-[170px] md:pr-5 md:max-w-[300px] md:sticky md:top-80 | xl:pr-8 xl:w-[250px] | border-primary-light dark:border-primary-dark'>
								<p className='font-bold text-primary-light  dark:text-primary-dark '>Project purpose and goals</p>
								<p>Web Stack and Explanation</p>
								<p>Problems and thought process</p>
								<p>Future Improvements</p>
							</div>
							<div>
								<div className='space-y-3'>
									<h2 className='text-3xl font-bold  pb-3'>Project Purpose</h2>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et odio sed mi posuere
										tempus at eu nulla. Aenean lobortis purus posuere est vehicula semper. Vivamus nec lacus
										varius, ullamcorper orci sit amet, elementum dolor. Ut eu ex id dui suscipit condimentum.
										Suspendisse id nulla nulla. Donec mattis diam auctor enim condimentum, vitae lobortis
										ipsum pharetra. Nam sed vehicula mi. Maecenas nec facilisis lorem. Donec vel justo
										condimentum, lacinia risus varius, blandit libero. Phasellus pharetra vulputate leo, vel
										laoreet diam hendrerit eu. Sed sit amet volutpat nisi.
									</p>
									<p>
										Integer congue diam lectus, sed suscipit nulla tempor vitae. Maecenas eu mollis odio. Duis
										ac odio iaculis, euismod dolor nec, varius mi. Aliquam eu volutpat tellus, a eleifend
										nibh. Duis finibus convallis egestas. Phasellus sed felis et justo cursus feugiat. Integer
										volutpat metus ut lorem imperdiet tincidunt. Ut facilisis, turpis vel dictum gravida,
										velit lacus dictum eros, nec fringilla mi quam sit amet urna. Proin nec massa aliquet,
										hendrerit nulla eu, blandit enim. Sed at egestas nibh.
									</p>
									<p>
										Nam mattis fringilla quam. Mauris porta sodales diam, nec blandit ante sollicitudin et.
										Nullam non suscipit erat. Maecenas accumsan volutpat nibh non hendrerit. Duis auctor
										placerat ex, quis euismod libero. Nam mattis vel nunc vitae hendrerit. Aliquam nec mi in
										odio fringilla facilisis. Integer rutrum sagittis tempor. In aliquet porttitor blandit.
										Praesent convallis leo tempus justo vestibulum, vel lacinia purus varius.
									</p>
								</div>

								<div className='my-20'>
									<ImageCard cover={project.cover} className='h-[600px]' />
								</div>
								<div className='my-10 space-y-3'>
									<h2 className='text-3xl font-bold pb-3'>Web Stack and Explanation</h2>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et odio sed mi posuere
										tempus at eu nulla. Aenean lobortis purus posuere est vehicula semper. Vivamus nec lacus
										varius, ullamcorper orci sit amet, elementum dolor. Ut eu ex id dui suscipit condimentum.
										Suspendisse id nulla nulla. Donec mattis diam auctor enim condimentum, vitae lobortis
										ipsum pharetra. Nam sed vehicula mi. Maecenas nec facilisis lorem. Donec vel justo
										condimentum, lacinia risus varius, blandit libero. Phasellus pharetra vulputate leo, vel
										laoreet diam hendrerit eu. Sed sit amet volutpat nisi.
									</p>
									<p>
										Integer congue diam lectus, sed suscipit nulla tempor vitae. Maecenas eu mollis odio. Duis
										ac odio iaculis, euismod dolor nec, varius mi. Aliquam eu volutpat tellus, a eleifend
										nibh. Duis finibus convallis egestas. Phasellus sed felis et justo cursus feugiat. Integer
										volutpat metus ut lorem imperdiet tincidunt. Ut facilisis, turpis vel dictum gravida,
										velit lacus dictum eros, nec fringilla mi quam sit amet urna. Proin nec massa aliquet,
										hendrerit nulla eu, blandit enim. Sed at egestas nibh.
									</p>
									<p>
										Nam mattis fringilla quam. Mauris porta sodales diam, nec blandit ante sollicitudin et.
										Nullam non suscipit erat. Maecenas accumsan volutpat nibh non hendrerit. Duis auctor
										placerat ex, quis euismod libero. Nam mattis vel nunc vitae hendrerit. Aliquam nec mi in
										odio fringilla facilisis. Integer rutrum sagittis tempor. In aliquet porttitor blandit.
										Praesent convallis leo tempus justo vestibulum, vel lacinia purus varius.
									</p>
									<h2 className='text-3xl font-bold  pt-10 pb-3'>Project Purpose</h2>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam et odio sed mi posuere
										tempus at eu nulla. Aenean lobortis purus posuere est vehicula semper. Vivamus nec lacus
										varius, ullamcorper orci sit amet, elementum dolor. Ut eu ex id dui suscipit condimentum.
										Suspendisse id nulla nulla. Donec mattis diam auctor enim condimentum, vitae lobortis
										ipsum pharetra. Nam sed vehicula mi. Maecenas nec facilisis lorem. Donec vel justo
										condimentum, lacinia risus varius, blandit libero. Phasellus pharetra vulputate leo, vel
										laoreet diam hendrerit eu. Sed sit amet volutpat nisi.
									</p>
									<p>
										Integer congue diam lectus, sed suscipit nulla tempor vitae. Maecenas eu mollis odio. Duis
										ac odio iaculis, euismod dolor nec, varius mi. Aliquam eu volutpat tellus, a eleifend
										nibh. Duis finibus convallis egestas. Phasellus sed felis et justo cursus feugiat. Integer
										volutpat metus ut lorem imperdiet tincidunt. Ut facilisis, turpis vel dictum gravida,
										velit lacus dictum eros, nec fringilla mi quam sit amet urna. Proin nec massa aliquet,
										hendrerit nulla eu, blandit enim. Sed at egestas nibh.
									</p>
									<p>
										Nam mattis fringilla quam. Mauris porta sodales diam, nec blandit ante sollicitudin et.
										Nullam non suscipit erat. Maecenas accumsan volutpat nibh non hendrerit. Duis auctor
										placerat ex, quis euismod libero. Nam mattis vel nunc vitae hendrerit. Aliquam nec mi in
										odio fringilla facilisis. Integer rutrum sagittis tempor. In aliquet porttitor blandit.
										Praesent convallis leo tempus justo vestibulum, vel lacinia purus varius.
									</p>
								</div>
							</div>
						</div>
					</div>
					<div className='my:20 md:my-32 md:w-4/6 mx-auto'>
						<h2 className='text-4xl  font-bold mb-14'>See more projects</h2>
						<div className=' grid md:grid-cols-2 gap-28'>
							<div>
								<ImageCard cover={project.cover} className='h-80' />
								<h3 className='text-2xl font-bold mt-6 mb-3'>Audiophile</h3>
								<p> Nam mattis fringilla quam. Mauris porta sodales diam, nec blandit ante sollicitudin et.</p>
								<a className='font-bold underline mt-3 inline-block'>View project</a>
							</div>
							<div>
								<ImageCard cover={project.cover} className='h-80' />
								<h3 className='text-2xl font-bold mt-6 mb-3'>Life is Mine</h3>
								<p> Nam mattis fringilla quam. Mauris porta sodales diam, nec blandit ante sollicitudin et.</p>
								<a className='font-bold underline mt-3 inline-block'>View project</a>
							</div>
						</div>
					</div>
				</Container>
			</div>
		</>
	);
}

export async function getStaticProps(): Promise<any> {
	const query = await client.query({
		query: gql`
			query Project {
				projects(where: { name: "Jerry" }) {
					name
					id
					content
					description
					cover {
						height
						width
						url
						alternativeText
					}
					skills {
						name
						icon {
							url
							height
							width
						}
					}
					slug
					tags {
						name
					}
				}
			}
		`,
	});

	return {
		props: {
			project: query.data.projects[0],
			revalidate: 10,
		},
	};
}
